# Dieses Script liest eine CSV-Datendatei in GNU R ein.
# Beim Einlesen werden für alle Variablen Beschriftungen (comment) angelegt.
# Die Beschriftungen für Werte wird ebenfalls als Attribute (attr) abgelegt.

all_data_file = file.choose()
# setwd("./")
# all_data_file = "rdata_lernplaner_srl_remastered_2021-04-10_14-08.csv"

all_data = read.table(
  file=all_data_file, encoding="UTF-8",
  header = FALSE, sep = "\t", quote = "\"",
  dec = ".", row.names = "CASE",
  col.names = c(
    "CASE","SERIAL","REF","QUESTNNR","MODE","STARTED","EE02","DD02_01","DD03",
    "DD04_01","DD05","DD05_12","DD06_01","DD06_02","DD07","DD09","DD11","DD10_01",
    "DD10_02","DD10_03","DD10_04","DD10_05","DD10_06","DD10_07","DD10_08","LP02_01",
    "LP03_01","LP03_02","LP05","LP06_01","LP07_01","LP07_02","LP09","LP10_01",
    "LP11_01","LP11_02","LP13","T102_01","T102_02","T102_03","T102_04","T103_01",
    "T103_02","T103_03","T104_01","T104_02","T104_03","T104_04","T105_01","T105_02",
    "T105_03","T106_01","T106_02","T106_03","T107_01","T107_02","T107_03","T107_04",
    "T107_05","T107_06","T107_07","T108_01","T108_02","T108_03","T108_04","T108_05",
    "T108_06","T108_07","T108_08","T108_09","T202_01","T202_02","T202_03","T202_04",
    "T203_01","T203_02","T203_03","T204_01","T204_02","T204_03","T204_04","T205_01",
    "T205_02","T205_03","T206_01","T206_02","T206_03","T207_01","T207_02","T207_03",
    "T207_04","T207_05","T207_06","T207_07","T208_01","T208_02","T208_03","T208_04",
    "T208_05","T208_06","T208_07","T208_08","T208_09","KO01","EM01_04","EM02",
    "EM03","EM04","EV02_01","EV02_02","EV02_03","EV02_04","EV02_05","EV02_06",
    "EV03_01","EV04_01","EV04_02","EV04_03","EV04_04","EV04_05","FA02_01","FA02_02",
    "FA02_03","FA02_04","FA02_05","FA02_06","FA02_07","FA02_08","FA02_09","FA02_10",
    "FA02_11","FA02_12","FA02_13","FA02_14","FA02_15","FA02_16","FA02_17","FA02_18",
    "FA02_19","FA02_20","FA02_21","FA02_22","FA02_23","FA02_24","FA02_25","FA02_26",
    "FA02_27","FA02_28","FA02_29","FA02_30","FA02_31","FA02_32","FA02_33","FA02_34",
    "FA02_35","FA02_36","FA02_37","PT02","PT03_01","PT04","PT05_01","PT06",
    "PT07_01","LZ02_01","LZ03_01","LZ04_01","ZE02_01","ZE03_01","PL01_01","PL02_01",
    "SM02_01","SM02_02","SM02_03","SE01_03","TE_Bel_1","TE_Bel_2","TE_Bel_3",
    "TE_Bel_4","TE_Bel_5","TE_Bel_6","TE03_01","TE04_01","TE05_01","TE06_01",
    "TE07_01","TE08_01","TE09_01","TE10_01","TE11_01","TE12_01","TE13_01","TE14_01",
    "TE15_01","TE16","TE17_01","ZG01_CP","ZG01","ZG02_CP","ZG02","ZG03_CP","ZG03",
    "ZG04_CP","ZG04","ZG05_CP","ZG05","ZG06_CP","ZG06","ZG07_CP","ZG07","ZG08_CP",
    "ZG08","ZG09_CP","ZG09","ZG10_CP","ZG10","ZG11_CP","ZG11","ZG15_CP","ZG15",
    "ZG16_CP","ZG16","ZG17_CP","ZG17","ZG18_CP","ZG18","ZG19_CP","ZG19","ZG20_CP",
    "ZG20","ZG21_CP","ZG21","ZG22_CP","ZG22","ZG23_CP","ZG23","ZG24_CP","ZG24",
    "ZG25_CP","ZG25","ZG26_CP","ZG26","ZG27_CP","ZG27","ZG28_CP","ZG28","ZG29_CP",
    "ZG29","ZG30_CP","ZG30","ZG31_CP","ZG31","ZG32_CP","ZG32","ZG33_CP","ZG33",
    "ZG34_CP","ZG34","ZG35_CP","ZG35","ZG36_CP","ZG36","ZG37_CP","ZG37","ZG38_CP",
    "ZG38","AI01_pts","AI01_rgs","AI01_01","AI02_01","AI06_01","AI12_01","AV02_01",
    "AV02_02","AV02_03","AV02_04","AV02_05","AV03_01","AV03_02","AV03_03","AV03_04",
    "AV03_05","AV04_01","AV04_02","AV04_03","AV05_01","AV05_02","AV05_03","AV05_04",
    "AV06_01","AV06_02","AV06_03","AV07_01","AV07_02","AV07_03","AV07_04","AV09_01",
    "AV09_02","AV09_03","AV10_01","AV10_02","AV10_03","TIME001","TIME002","TIME003",
    "TIME004","TIME005","TIME006","TIME007","TIME008","TIME009","TIME010","TIME011",
    "TIME012","TIME013","TIME014","TIME015","TIME016","TIME017","TIME018","TIME019",
    "TIME_SUM","MAILSENT","LASTDATA","FINISHED","Q_VIEWER","LASTPAGE","MAXPAGE",
    "MISSING","MISSREL","TIME_RSI","DEG_TIME"
  ),
  as.is = TRUE,
  colClasses = c(
    CASE="numeric", SERIAL="character", REF="character", QUESTNNR="character",
    MODE="character", STARTED="POSIXct", EE02="numeric", DD02_01="character",
    DD03="numeric", DD04_01="numeric", DD05="numeric", DD05_12="character",
    DD06_01="character", DD06_02="character", DD07="numeric", DD09="numeric",
    DD11="numeric", DD10_01="numeric", DD10_02="numeric", DD10_03="numeric",
    DD10_04="numeric", DD10_05="numeric", DD10_06="numeric", DD10_07="numeric",
    DD10_08="numeric", LP02_01="Date", LP03_01="numeric", LP03_02="numeric",
    LP05="numeric", LP06_01="Date", LP07_01="numeric", LP07_02="numeric",
    LP09="numeric", LP10_01="Date", LP11_01="numeric", LP11_02="numeric",
    LP13="numeric", T102_01="numeric", T102_02="numeric", T102_03="numeric",
    T102_04="numeric", T103_01="numeric", T103_02="numeric", T103_03="numeric",
    T104_01="numeric", T104_02="numeric", T104_03="numeric", T104_04="numeric",
    T105_01="numeric", T105_02="numeric", T105_03="numeric", T106_01="numeric",
    T106_02="numeric", T106_03="numeric", T107_01="numeric", T107_02="numeric",
    T107_03="numeric", T107_04="numeric", T107_05="numeric", T107_06="numeric",
    T107_07="numeric", T108_01="numeric", T108_02="numeric", T108_03="numeric",
    T108_04="numeric", T108_05="numeric", T108_06="numeric", T108_07="numeric",
    T108_08="numeric", T108_09="numeric", T202_01="numeric", T202_02="numeric",
    T202_03="numeric", T202_04="numeric", T203_01="numeric", T203_02="numeric",
    T203_03="numeric", T204_01="numeric", T204_02="numeric", T204_03="numeric",
    T204_04="numeric", T205_01="numeric", T205_02="numeric", T205_03="numeric",
    T206_01="numeric", T206_02="numeric", T206_03="numeric", T207_01="numeric",
    T207_02="numeric", T207_03="numeric", T207_04="numeric", T207_05="numeric",
    T207_06="numeric", T207_07="numeric", T208_01="numeric", T208_02="numeric",
    T208_03="numeric", T208_04="numeric", T208_05="numeric", T208_06="numeric",
    T208_07="numeric", T208_08="numeric", T208_09="numeric", KO01="numeric",
    EM01_04="character", EM02="numeric", EM03="numeric", EM04="numeric",
    EV02_01="numeric", EV02_02="numeric", EV02_03="numeric", EV02_04="numeric",
    EV02_05="numeric", EV02_06="numeric", EV03_01="character",
    EV04_01="numeric", EV04_02="numeric", EV04_03="numeric", EV04_04="numeric",
    EV04_05="numeric", FA02_01="numeric", FA02_02="numeric", FA02_03="numeric",
    FA02_04="numeric", FA02_05="numeric", FA02_06="numeric", FA02_07="numeric",
    FA02_08="numeric", FA02_09="numeric", FA02_10="numeric", FA02_11="numeric",
    FA02_12="numeric", FA02_13="numeric", FA02_14="numeric", FA02_15="numeric",
    FA02_16="numeric", FA02_17="numeric", FA02_18="numeric", FA02_19="numeric",
    FA02_20="numeric", FA02_21="numeric", FA02_22="numeric", FA02_23="numeric",
    FA02_24="numeric", FA02_25="numeric", FA02_26="numeric", FA02_27="numeric",
    FA02_28="numeric", FA02_29="numeric", FA02_30="numeric", FA02_31="numeric",
    FA02_32="numeric", FA02_33="numeric", FA02_34="numeric", FA02_35="numeric",
    FA02_36="numeric", FA02_37="numeric", PT02="numeric", PT03_01="numeric",
    PT04="numeric", PT05_01="numeric", PT06="numeric", PT07_01="numeric",
    LZ02_01="character", LZ03_01="numeric", LZ04_01="numeric",
    ZE02_01="character", ZE03_01="character", PL01_01="numeric",
    PL02_01="character", SM02_01="numeric", SM02_02="numeric",
    SM02_03="numeric", SE01_03="numeric", TE_Bel_1="numeric",
    TE_Bel_2="numeric", TE_Bel_3="numeric", TE_Bel_4="numeric",
    TE_Bel_5="numeric", TE_Bel_6="numeric", TE03_01="numeric",
    TE04_01="character", TE05_01="character", TE06_01="numeric",
    TE07_01="numeric", TE08_01="numeric", TE09_01="numeric", TE10_01="numeric",
    TE11_01="numeric", TE12_01="numeric", TE13_01="character",
    TE14_01="numeric", TE15_01="numeric", TE16="numeric", TE17_01="numeric",
    ZG01_CP="numeric", ZG01="numeric", ZG02_CP="numeric", ZG02="numeric",
    ZG03_CP="numeric", ZG03="numeric", ZG04_CP="numeric", ZG04="numeric",
    ZG05_CP="numeric", ZG05="numeric", ZG06_CP="numeric", ZG06="numeric",
    ZG07_CP="numeric", ZG07="numeric", ZG08_CP="numeric", ZG08="numeric",
    ZG09_CP="numeric", ZG09="numeric", ZG10_CP="numeric", ZG10="numeric",
    ZG11_CP="numeric", ZG11="numeric", ZG15_CP="numeric", ZG15="numeric",
    ZG16_CP="numeric", ZG16="numeric", ZG17_CP="numeric", ZG17="numeric",
    ZG18_CP="numeric", ZG18="numeric", ZG19_CP="numeric", ZG19="numeric",
    ZG20_CP="numeric", ZG20="numeric", ZG21_CP="numeric", ZG21="numeric",
    ZG22_CP="numeric", ZG22="numeric", ZG23_CP="numeric", ZG23="numeric",
    ZG24_CP="numeric", ZG24="numeric", ZG25_CP="numeric", ZG25="numeric",
    ZG26_CP="numeric", ZG26="numeric", ZG27_CP="numeric", ZG27="numeric",
    ZG28_CP="numeric", ZG28="numeric", ZG29_CP="numeric", ZG29="numeric",
    ZG30_CP="numeric", ZG30="numeric", ZG31_CP="numeric", ZG31="numeric",
    ZG32_CP="numeric", ZG32="numeric", ZG33_CP="numeric", ZG33="numeric",
    ZG34_CP="numeric", ZG34="numeric", ZG35_CP="numeric", ZG35="numeric",
    ZG36_CP="numeric", ZG36="numeric", ZG37_CP="numeric", ZG37="numeric",
    ZG38_CP="numeric", ZG38="numeric", AI01_pts="character",
    AI01_rgs="character", AI01_01="numeric", AI02_01="character",
    AI06_01="character", AI12_01="character", AV02_01="numeric",
    AV02_02="numeric", AV02_03="numeric", AV02_04="numeric", AV02_05="numeric",
    AV03_01="numeric", AV03_02="numeric", AV03_03="numeric", AV03_04="numeric",
    AV03_05="numeric", AV04_01="numeric", AV04_02="numeric", AV04_03="numeric",
    AV05_01="numeric", AV05_02="numeric", AV05_03="numeric", AV05_04="numeric",
    AV06_01="numeric", AV06_02="numeric", AV06_03="numeric", AV07_01="numeric",
    AV07_02="numeric", AV07_03="numeric", AV07_04="numeric", AV09_01="numeric",
    AV09_02="numeric", AV09_03="numeric", AV10_01="numeric", AV10_02="numeric",
    AV10_03="numeric", TIME001="integer", TIME002="integer", TIME003="integer",
    TIME004="integer", TIME005="integer", TIME006="integer", TIME007="integer",
    TIME008="integer", TIME009="integer", TIME010="integer", TIME011="integer",
    TIME012="integer", TIME013="integer", TIME014="integer", TIME015="integer",
    TIME016="integer", TIME017="integer", TIME018="integer", TIME019="integer",
    TIME_SUM="integer", MAILSENT="POSIXct", LASTDATA="POSIXct",
    FINISHED="logical", Q_VIEWER="logical", LASTPAGE="numeric",
    MAXPAGE="numeric", MISSING="numeric", MISSREL="numeric", TIME_RSI="numeric",
    DEG_TIME="numeric"
  ),
  skip = 1,
  check.names = TRUE, fill = TRUE,
  strip.white = FALSE, blank.lines.skip = TRUE,
  comment.char = "",
  na.strings = ""
)

rm(all_data_file)

attr(all_data, "project") = "lernplaner_srl_remastered"
attr(all_data, "description") = "Lernplaner_SRL_Remastered"
attr(all_data, "date") = "2021-04-10 14:08:41"
attr(all_data, "server") = "https://www.soscisurvey.de"

# Variable und Value Labels
all_data$EE02 = factor(all_data$EE02, levels=c("1","2","-9"), labels=c("Ja.","Nein. (Die anonymisierten Daten dürfen nicht für wissenschaftliche Zwecke verwendet werden.)","[NA] nicht beantwortet"), ordered=FALSE)
all_data$DD03 = factor(all_data$DD03, levels=c("1","2","3","4","-9"), labels=c("weiblich","männlich","divers","keine Angabe","[NA] nicht beantwortet"), ordered=FALSE)
all_data$DD05 = factor(all_data$DD05, levels=c("1","2","3","4","5","6","7","8","9","10","11","12","-9"), labels=c("Bachelor (B.A.)","Bachelor (B.Sc.)","Bachelor (B.Ed.)","Bachelor (B.Mus.)","Magister","Master (M.A.)","Master (M.Sc.)","Master (M.Ed.)","Master (LL.M.)","Diplom","Staatsexamen","Sonstiges","[NA] nicht beantwortet"), ordered=FALSE)
all_data$DD07 = factor(all_data$DD07, levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","-9"), labels=c("1,0","1,1","1,2","1,3","1,4","1,5","1,6","1,7","1,8","1,9","2,0","2,1","2,2","2,3","2,4","2,5","2,6","2,7","2,8","2,9","3,0","3,1","3,2","3,3","3,4","3,5","3,6","3,7","3,8","3,9","4,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$DD09 = factor(all_data$DD09, levels=c("1","2","-9"), labels=c("Ja.","Nein.","[NA] nicht beantwortet"), ordered=FALSE)
all_data$DD11 = factor(all_data$DD11, levels=c("1","2","-9"), labels=c("Ja.","Nein.","[NA] nicht beantwortet"), ordered=FALSE)
all_data$LP05 = factor(all_data$LP05, levels=c("1","2","3","4","5","6","7","8","9","10","11","-9"), labels=c("1,0","1,3","1,7","2,0","2,3","2,7","3,0","3,3","3,7","4,0","5,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$LP09 = factor(all_data$LP09, levels=c("1","2","3","4","5","6","7","8","9","10","11","-9"), labels=c("1,0","1,3","1,7","2,0","2,3","2,7","3,0","3,3","3,7","4,0","5,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$LP13 = factor(all_data$LP13, levels=c("1","2","3","4","5","6","7","8","9","10","11","-9"), labels=c("1,0","1,3","1,7","2,0","2,3","2,7","3,0","3,3","3,7","4,0","5,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$KO01 = factor(all_data$KO01, levels=c("1","2","3","-9"), labels=c("Völlig konzentriert und gewissenhaft.","Teilweise konzentriert und gewissenhaft.","Gar nicht konzentriert und gewissenhaft.","[NA] nicht beantwortet"), ordered=FALSE)
all_data$EM02 = factor(all_data$EM02, levels=c("1","2","3","4","5","6","7","8","-9"), labels=c("Spezielle Entwicklungspsychologische Aspekte des Lehrens und Lernens (Do 10-12 Uhr)","Spezielle Entwicklungspsychologische Aspekte des Lehrens und Lernens (Do 12-14 Uhr)","Spezielle Entwicklungspsychologische Aspekte des Lehrens und Lernens (Fr 10-12 Uhr)","Spezielle Entwicklungspsychologische Aspekte des Lehrens und Lernens (Fr 12-14 Uhr)","Kognition (Mo 14-16 Uhr)","Kognition (Mo 16-18 Uhr)","Kognition (Mi 10-12 Uhr)","Kognition (Mi 12-14 Uhr)","[NA] nicht beantwortet"), ordered=FALSE)
all_data$EM03 = factor(all_data$EM03, levels=c("1","2","3","-9"), labels=c("Sitzung von Hannah","Sitzung von Jakob","Ich habe an der Einführungsveranstaltung nicht teilgenommen.","[NA] nicht beantwortet"), ordered=FALSE)
all_data$EM04 = factor(all_data$EM04, levels=c("1","2","3","-9"), labels=c("Sitzung von Hannah","Sitzung von Jakob","Ich habe an der Sitzung zur Zwischenreflexion nicht teilgenommen.","[NA] nicht beantwortet"), ordered=FALSE)
all_data$PT02 = factor(all_data$PT02, levels=c("1","2","3","4","5","6","7","8","9","10","11","-9"), labels=c("1,0","1,3","1,7","2,0","2,3","2,7","3,0","3,3","3,7","4,0","5,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$PT04 = factor(all_data$PT04, levels=c("1","2","3","4","5","6","7","8","9","10","11","-9"), labels=c("1,0","1,3","1,7","2,0","2,3","2,7","3,0","3,3","3,7","4,0","5,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$PT06 = factor(all_data$PT06, levels=c("1","2","3","4","5","6","7","8","9","10","11","-9"), labels=c("1,0","1,3","1,7","2,0","2,3","2,7","3,0","3,3","3,7","4,0","5,0","[NA] nicht beantwortet"), ordered=FALSE)
all_data$TE16 = factor(all_data$TE16, levels=c("1","2","-9"), labels=c("Ja","Nein","[NA] nicht beantwortet"), ordered=FALSE)
attr(all_data$DD10_01,"1") = "gering"
attr(all_data$DD10_01,"6") = "hoch"
attr(all_data$DD10_02,"1") = "gering"
attr(all_data$DD10_02,"6") = "hoch"
attr(all_data$DD10_03,"1") = "gering"
attr(all_data$DD10_03,"6") = "hoch"
attr(all_data$DD10_04,"1") = "gering"
attr(all_data$DD10_04,"6") = "hoch"
attr(all_data$DD10_05,"1") = "gering"
attr(all_data$DD10_05,"6") = "hoch"
attr(all_data$DD10_06,"1") = "gering"
attr(all_data$DD10_06,"6") = "hoch"
attr(all_data$DD10_07,"1") = "gering"
attr(all_data$DD10_07,"6") = "hoch"
attr(all_data$DD10_08,"1") = "gering"
attr(all_data$DD10_08,"6") = "hoch"
attr(all_data$LP03_01,"1") = "gar nicht anspruchsvoll"
attr(all_data$LP03_01,"6") = "sehr anspruchsvoll"
attr(all_data$LP03_02,"1") = "gar nicht anspruchsvoll"
attr(all_data$LP03_02,"6") = "sehr anspruchsvoll"
attr(all_data$LP07_01,"1") = "gar nicht anspruchsvoll"
attr(all_data$LP07_01,"6") = "sehr anspruchsvoll"
attr(all_data$LP07_02,"1") = "gar nicht anspruchsvoll"
attr(all_data$LP07_02,"6") = "sehr anspruchsvoll"
attr(all_data$LP11_01,"1") = "gar nicht anspruchsvoll"
attr(all_data$LP11_01,"6") = "sehr anspruchsvoll"
attr(all_data$LP11_02,"1") = "gar nicht anspruchsvoll"
attr(all_data$LP11_02,"6") = "sehr anspruchsvoll"
attr(all_data$T102_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T102_01,"6") = "stimme völlig zu"
attr(all_data$T102_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T102_02,"6") = "stimme völlig zu"
attr(all_data$T102_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T102_03,"6") = "stimme völlig zu"
attr(all_data$T102_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T102_04,"6") = "stimme völlig zu"
attr(all_data$T103_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T103_01,"6") = "stimme völlig zu"
attr(all_data$T103_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T103_02,"6") = "stimme völlig zu"
attr(all_data$T103_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T103_03,"6") = "stimme völlig zu"
attr(all_data$T104_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T104_01,"6") = "stimme völlig zu"
attr(all_data$T104_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T104_02,"6") = "stimme völlig zu"
attr(all_data$T104_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T104_03,"6") = "stimme völlig zu"
attr(all_data$T104_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T104_04,"6") = "stimme völlig zu"
attr(all_data$T105_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T105_01,"6") = "stimme völlig zu"
attr(all_data$T105_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T105_02,"6") = "stimme völlig zu"
attr(all_data$T105_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T105_03,"6") = "stimme völlig zu"
attr(all_data$T106_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T106_01,"6") = "stimme völlig zu"
attr(all_data$T106_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T106_02,"6") = "stimme völlig zu"
attr(all_data$T106_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T106_03,"6") = "stimme völlig zu"
attr(all_data$T107_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_01,"6") = "stimme völlig zu"
attr(all_data$T107_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_02,"6") = "stimme völlig zu"
attr(all_data$T107_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_03,"6") = "stimme völlig zu"
attr(all_data$T107_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_04,"6") = "stimme völlig zu"
attr(all_data$T107_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_05,"6") = "stimme völlig zu"
attr(all_data$T107_06,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_06,"6") = "stimme völlig zu"
attr(all_data$T107_07,"1") = "stimme überhaupt nicht zu"
attr(all_data$T107_07,"6") = "stimme völlig zu"
attr(all_data$T108_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_01,"6") = "stimme völlig zu"
attr(all_data$T108_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_02,"6") = "stimme völlig zu"
attr(all_data$T108_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_03,"6") = "stimme völlig zu"
attr(all_data$T108_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_04,"6") = "stimme völlig zu"
attr(all_data$T108_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_05,"6") = "stimme völlig zu"
attr(all_data$T108_06,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_06,"6") = "stimme völlig zu"
attr(all_data$T108_07,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_07,"6") = "stimme völlig zu"
attr(all_data$T108_08,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_08,"6") = "stimme völlig zu"
attr(all_data$T108_09,"1") = "stimme überhaupt nicht zu"
attr(all_data$T108_09,"6") = "stimme völlig zu"
attr(all_data$T202_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T202_01,"6") = "stimme völlig zu"
attr(all_data$T202_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T202_02,"6") = "stimme völlig zu"
attr(all_data$T202_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T202_03,"6") = "stimme völlig zu"
attr(all_data$T202_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T202_04,"6") = "stimme völlig zu"
attr(all_data$T203_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T203_01,"6") = "stimme völlig zu"
attr(all_data$T203_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T203_02,"6") = "stimme völlig zu"
attr(all_data$T203_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T203_03,"6") = "stimme völlig zu"
attr(all_data$T204_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T204_01,"6") = "stimme völlig zu"
attr(all_data$T204_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T204_02,"6") = "stimme völlig zu"
attr(all_data$T204_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T204_03,"6") = "stimme völlig zu"
attr(all_data$T204_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T204_04,"6") = "stimme völlig zu"
attr(all_data$T205_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T205_01,"6") = "stimme völlig zu"
attr(all_data$T205_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T205_02,"6") = "stimme völlig zu"
attr(all_data$T205_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T205_03,"6") = "stimme völlig zu"
attr(all_data$T206_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T206_01,"6") = "stimme völlig zu"
attr(all_data$T206_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T206_02,"6") = "stimme völlig zu"
attr(all_data$T206_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T206_03,"6") = "stimme völlig zu"
attr(all_data$T207_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_01,"6") = "stimme völlig zu"
attr(all_data$T207_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_02,"6") = "stimme völlig zu"
attr(all_data$T207_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_03,"6") = "stimme völlig zu"
attr(all_data$T207_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_04,"6") = "stimme völlig zu"
attr(all_data$T207_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_05,"6") = "stimme völlig zu"
attr(all_data$T207_06,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_06,"6") = "stimme völlig zu"
attr(all_data$T207_07,"1") = "stimme überhaupt nicht zu"
attr(all_data$T207_07,"6") = "stimme völlig zu"
attr(all_data$T208_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_01,"6") = "stimme völlig zu"
attr(all_data$T208_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_02,"6") = "stimme völlig zu"
attr(all_data$T208_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_03,"6") = "stimme völlig zu"
attr(all_data$T208_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_04,"6") = "stimme völlig zu"
attr(all_data$T208_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_05,"6") = "stimme völlig zu"
attr(all_data$T208_06,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_06,"6") = "stimme völlig zu"
attr(all_data$T208_07,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_07,"6") = "stimme völlig zu"
attr(all_data$T208_08,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_08,"6") = "stimme völlig zu"
attr(all_data$T208_09,"1") = "stimme überhaupt nicht zu"
attr(all_data$T208_09,"6") = "stimme völlig zu"
attr(all_data$EV02_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV02_01,"6") = "stimme völlig zu"
attr(all_data$EV02_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV02_02,"6") = "stimme völlig zu"
attr(all_data$EV02_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV02_03,"6") = "stimme völlig zu"
attr(all_data$EV02_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV02_04,"6") = "stimme völlig zu"
attr(all_data$EV02_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV02_05,"6") = "stimme völlig zu"
attr(all_data$EV02_06,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV02_06,"6") = "stimme völlig zu"
attr(all_data$EV04_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV04_01,"6") = "stimme völlig zu"
attr(all_data$EV04_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV04_02,"6") = "stimme völlig zu"
attr(all_data$EV04_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV04_03,"6") = "stimme völlig zu"
attr(all_data$EV04_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV04_04,"6") = "stimme völlig zu"
attr(all_data$EV04_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$EV04_05,"6") = "stimme völlig zu"
attr(all_data$FA02_01,"1") = "fast nie"
attr(all_data$FA02_01,"2") = "selten"
attr(all_data$FA02_01,"3") = "eher selten"
attr(all_data$FA02_01,"4") = "eher häufig"
attr(all_data$FA02_01,"5") = "häufig"
attr(all_data$FA02_01,"6") = "fast immer"
attr(all_data$FA02_02,"1") = "fast nie"
attr(all_data$FA02_02,"2") = "selten"
attr(all_data$FA02_02,"3") = "eher selten"
attr(all_data$FA02_02,"4") = "eher häufig"
attr(all_data$FA02_02,"5") = "häufig"
attr(all_data$FA02_02,"6") = "fast immer"
attr(all_data$FA02_03,"1") = "fast nie"
attr(all_data$FA02_03,"2") = "selten"
attr(all_data$FA02_03,"3") = "eher selten"
attr(all_data$FA02_03,"4") = "eher häufig"
attr(all_data$FA02_03,"5") = "häufig"
attr(all_data$FA02_03,"6") = "fast immer"
attr(all_data$FA02_04,"1") = "fast nie"
attr(all_data$FA02_04,"2") = "selten"
attr(all_data$FA02_04,"3") = "eher selten"
attr(all_data$FA02_04,"4") = "eher häufig"
attr(all_data$FA02_04,"5") = "häufig"
attr(all_data$FA02_04,"6") = "fast immer"
attr(all_data$FA02_05,"1") = "fast nie"
attr(all_data$FA02_05,"2") = "selten"
attr(all_data$FA02_05,"3") = "eher selten"
attr(all_data$FA02_05,"4") = "eher häufig"
attr(all_data$FA02_05,"5") = "häufig"
attr(all_data$FA02_05,"6") = "fast immer"
attr(all_data$FA02_06,"1") = "fast nie"
attr(all_data$FA02_06,"2") = "selten"
attr(all_data$FA02_06,"3") = "eher selten"
attr(all_data$FA02_06,"4") = "eher häufig"
attr(all_data$FA02_06,"5") = "häufig"
attr(all_data$FA02_06,"6") = "fast immer"
attr(all_data$FA02_07,"1") = "fast immer"
attr(all_data$FA02_07,"2") = "häufig"
attr(all_data$FA02_07,"3") = "eher häufig"
attr(all_data$FA02_07,"4") = "eher selten"
attr(all_data$FA02_07,"5") = "selten"
attr(all_data$FA02_07,"6") = "fast nie"
attr(all_data$FA02_08,"1") = "fast nie"
attr(all_data$FA02_08,"2") = "selten"
attr(all_data$FA02_08,"3") = "eher selten"
attr(all_data$FA02_08,"4") = "eher häufig"
attr(all_data$FA02_08,"5") = "häufig"
attr(all_data$FA02_08,"6") = "fast immer"
attr(all_data$FA02_09,"1") = "fast nie"
attr(all_data$FA02_09,"2") = "selten"
attr(all_data$FA02_09,"3") = "eher selten"
attr(all_data$FA02_09,"4") = "eher häufig"
attr(all_data$FA02_09,"5") = "häufig"
attr(all_data$FA02_09,"6") = "fast immer"
attr(all_data$FA02_10,"1") = "fast immer"
attr(all_data$FA02_10,"2") = "häufig"
attr(all_data$FA02_10,"3") = "eher häufig"
attr(all_data$FA02_10,"4") = "eher selten"
attr(all_data$FA02_10,"5") = "selten"
attr(all_data$FA02_10,"6") = "fast nie"
attr(all_data$FA02_11,"1") = "fast nie"
attr(all_data$FA02_11,"2") = "selten"
attr(all_data$FA02_11,"3") = "eher selten"
attr(all_data$FA02_11,"4") = "eher häufig"
attr(all_data$FA02_11,"5") = "häufig"
attr(all_data$FA02_11,"6") = "fast immer"
attr(all_data$FA02_12,"1") = "fast nie"
attr(all_data$FA02_12,"2") = "selten"
attr(all_data$FA02_12,"3") = "eher selten"
attr(all_data$FA02_12,"4") = "eher häufig"
attr(all_data$FA02_12,"5") = "häufig"
attr(all_data$FA02_12,"6") = "fast immer"
attr(all_data$FA02_13,"1") = "fast nie"
attr(all_data$FA02_13,"2") = "selten"
attr(all_data$FA02_13,"3") = "eher selten"
attr(all_data$FA02_13,"4") = "eher häufig"
attr(all_data$FA02_13,"5") = "häufig"
attr(all_data$FA02_13,"6") = "fast immer"
attr(all_data$FA02_14,"1") = "fast nie"
attr(all_data$FA02_14,"2") = "selten"
attr(all_data$FA02_14,"3") = "eher selten"
attr(all_data$FA02_14,"4") = "eher häufig"
attr(all_data$FA02_14,"5") = "häufig"
attr(all_data$FA02_14,"6") = "fast immer"
attr(all_data$FA02_15,"1") = "fast nie"
attr(all_data$FA02_15,"2") = "selten"
attr(all_data$FA02_15,"3") = "eher selten"
attr(all_data$FA02_15,"4") = "eher häufig"
attr(all_data$FA02_15,"5") = "häufig"
attr(all_data$FA02_15,"6") = "fast immer"
attr(all_data$FA02_16,"1") = "fast nie"
attr(all_data$FA02_16,"2") = "selten"
attr(all_data$FA02_16,"3") = "eher selten"
attr(all_data$FA02_16,"4") = "eher häufig"
attr(all_data$FA02_16,"5") = "häufig"
attr(all_data$FA02_16,"6") = "fast immer"
attr(all_data$FA02_17,"1") = "fast immer"
attr(all_data$FA02_17,"2") = "häufig"
attr(all_data$FA02_17,"3") = "eher häufig"
attr(all_data$FA02_17,"4") = "eher selten"
attr(all_data$FA02_17,"5") = "selten"
attr(all_data$FA02_17,"6") = "fast nie"
attr(all_data$FA02_18,"1") = "fast nie"
attr(all_data$FA02_18,"2") = "selten"
attr(all_data$FA02_18,"3") = "eher selten"
attr(all_data$FA02_18,"4") = "eher häufig"
attr(all_data$FA02_18,"5") = "häufig"
attr(all_data$FA02_18,"6") = "fast immer"
attr(all_data$FA02_19,"1") = "fast immer"
attr(all_data$FA02_19,"2") = "häufig"
attr(all_data$FA02_19,"3") = "eher häufig"
attr(all_data$FA02_19,"4") = "eher selten"
attr(all_data$FA02_19,"5") = "selten"
attr(all_data$FA02_19,"6") = "fast nie"
attr(all_data$FA02_20,"1") = "fast nie"
attr(all_data$FA02_20,"2") = "selten"
attr(all_data$FA02_20,"3") = "eher selten"
attr(all_data$FA02_20,"4") = "eher häufig"
attr(all_data$FA02_20,"5") = "häufig"
attr(all_data$FA02_20,"6") = "fast immer"
attr(all_data$FA02_21,"1") = "fast nie"
attr(all_data$FA02_21,"2") = "selten"
attr(all_data$FA02_21,"3") = "eher selten"
attr(all_data$FA02_21,"4") = "eher häufig"
attr(all_data$FA02_21,"5") = "häufig"
attr(all_data$FA02_21,"6") = "fast immer"
attr(all_data$FA02_22,"1") = "fast immer"
attr(all_data$FA02_22,"2") = "häufig"
attr(all_data$FA02_22,"3") = "eher häufig"
attr(all_data$FA02_22,"4") = "eher selten"
attr(all_data$FA02_22,"5") = "selten"
attr(all_data$FA02_22,"6") = "fast nie"
attr(all_data$FA02_23,"1") = "fast nie"
attr(all_data$FA02_23,"2") = "selten"
attr(all_data$FA02_23,"3") = "eher selten"
attr(all_data$FA02_23,"4") = "eher häufig"
attr(all_data$FA02_23,"5") = "häufig"
attr(all_data$FA02_23,"6") = "fast immer"
attr(all_data$FA02_24,"1") = "fast nie"
attr(all_data$FA02_24,"2") = "selten"
attr(all_data$FA02_24,"3") = "eher selten"
attr(all_data$FA02_24,"4") = "eher häufig"
attr(all_data$FA02_24,"5") = "häufig"
attr(all_data$FA02_24,"6") = "fast immer"
attr(all_data$FA02_25,"1") = "fast nie"
attr(all_data$FA02_25,"2") = "selten"
attr(all_data$FA02_25,"3") = "eher selten"
attr(all_data$FA02_25,"4") = "eher häufig"
attr(all_data$FA02_25,"5") = "häufig"
attr(all_data$FA02_25,"6") = "fast immer"
attr(all_data$FA02_26,"1") = "fast immer"
attr(all_data$FA02_26,"2") = "häufig"
attr(all_data$FA02_26,"3") = "eher häufig"
attr(all_data$FA02_26,"4") = "eher selten"
attr(all_data$FA02_26,"5") = "selten"
attr(all_data$FA02_26,"6") = "fast nie"
attr(all_data$FA02_27,"1") = "fast nie"
attr(all_data$FA02_27,"2") = "selten"
attr(all_data$FA02_27,"3") = "eher selten"
attr(all_data$FA02_27,"4") = "eher häufig"
attr(all_data$FA02_27,"5") = "häufig"
attr(all_data$FA02_27,"6") = "fast immer"
attr(all_data$FA02_28,"1") = "fast nie"
attr(all_data$FA02_28,"2") = "selten"
attr(all_data$FA02_28,"3") = "eher selten"
attr(all_data$FA02_28,"4") = "eher häufig"
attr(all_data$FA02_28,"5") = "häufig"
attr(all_data$FA02_28,"6") = "fast immer"
attr(all_data$FA02_29,"1") = "fast nie"
attr(all_data$FA02_29,"2") = "selten"
attr(all_data$FA02_29,"3") = "eher selten"
attr(all_data$FA02_29,"4") = "eher häufig"
attr(all_data$FA02_29,"5") = "häufig"
attr(all_data$FA02_29,"6") = "fast immer"
attr(all_data$FA02_30,"1") = "fast immer"
attr(all_data$FA02_30,"2") = "häufig"
attr(all_data$FA02_30,"3") = "eher häufig"
attr(all_data$FA02_30,"4") = "eher selten"
attr(all_data$FA02_30,"5") = "selten"
attr(all_data$FA02_30,"6") = "fast nie"
attr(all_data$FA02_31,"1") = "fast nie"
attr(all_data$FA02_31,"2") = "selten"
attr(all_data$FA02_31,"3") = "eher selten"
attr(all_data$FA02_31,"4") = "eher häufig"
attr(all_data$FA02_31,"5") = "häufig"
attr(all_data$FA02_31,"6") = "fast immer"
attr(all_data$FA02_32,"1") = "fast nie"
attr(all_data$FA02_32,"2") = "selten"
attr(all_data$FA02_32,"3") = "eher selten"
attr(all_data$FA02_32,"4") = "eher häufig"
attr(all_data$FA02_32,"5") = "häufig"
attr(all_data$FA02_32,"6") = "fast immer"
attr(all_data$FA02_33,"1") = "fast immer"
attr(all_data$FA02_33,"2") = "häufig"
attr(all_data$FA02_33,"3") = "eher häufig"
attr(all_data$FA02_33,"4") = "eher selten"
attr(all_data$FA02_33,"5") = "selten"
attr(all_data$FA02_33,"6") = "fast nie"
attr(all_data$FA02_34,"1") = "fast nie"
attr(all_data$FA02_34,"2") = "selten"
attr(all_data$FA02_34,"3") = "eher selten"
attr(all_data$FA02_34,"4") = "eher häufig"
attr(all_data$FA02_34,"5") = "häufig"
attr(all_data$FA02_34,"6") = "fast immer"
attr(all_data$FA02_35,"1") = "fast nie"
attr(all_data$FA02_35,"2") = "selten"
attr(all_data$FA02_35,"3") = "eher selten"
attr(all_data$FA02_35,"4") = "eher häufig"
attr(all_data$FA02_35,"5") = "häufig"
attr(all_data$FA02_35,"6") = "fast immer"
attr(all_data$FA02_36,"1") = "fast immer"
attr(all_data$FA02_36,"2") = "häufig"
attr(all_data$FA02_36,"3") = "eher häufig"
attr(all_data$FA02_36,"4") = "eher selten"
attr(all_data$FA02_36,"5") = "selten"
attr(all_data$FA02_36,"6") = "fast nie"
attr(all_data$FA02_37,"1") = "fast nie"
attr(all_data$FA02_37,"2") = "selten"
attr(all_data$FA02_37,"3") = "eher selten"
attr(all_data$FA02_37,"4") = "eher häufig"
attr(all_data$FA02_37,"5") = "häufig"
attr(all_data$FA02_37,"6") = "fast immer"
attr(all_data$PT03_01,"1") = "gar nicht zufrieden"
attr(all_data$PT03_01,"6") = "sehr zufrieden"
attr(all_data$PT05_01,"1") = "gar nicht zufrieden"
attr(all_data$PT05_01,"6") = "sehr zufrieden"
attr(all_data$PT07_01,"1") = "gar nicht zufrieden"
attr(all_data$PT07_01,"6") = "sehr zufrieden"
attr(all_data$LZ03_01,"1") = "unrealistisch"
attr(all_data$LZ03_01,"6") = "sehr realistisch"
attr(all_data$LZ04_01,"1") = "gar nicht anspruchsvoll"
attr(all_data$LZ04_01,"6") = "sehr anspruchsvoll"
attr(all_data$PL01_01,"1") = "stimme gar nicht zu"
attr(all_data$PL01_01,"6") = "stimme sehr zu"
attr(all_data$SM02_01,"1") = "gar nicht"
attr(all_data$SM02_01,"6") = "sehr"
attr(all_data$SM02_02,"1") = "gar nicht"
attr(all_data$SM02_02,"6") = "sehr"
attr(all_data$SM02_03,"1") = "gar nicht"
attr(all_data$SM02_03,"6") = "sehr"
attr(all_data$SE01_03,"1") = "stimme gar nicht zu"
attr(all_data$SE01_03,"6") = "stimme sehr zu"
attr(all_data$TE_Bel_1,"1") = "gar nicht"
attr(all_data$TE_Bel_1,"6") = "sehr"
attr(all_data$TE_Bel_2,"1") = "gar nicht"
attr(all_data$TE_Bel_2,"6") = "sehr"
attr(all_data$TE_Bel_3,"1") = "gar nicht"
attr(all_data$TE_Bel_3,"6") = "sehr"
attr(all_data$TE_Bel_4,"1") = "gar nicht"
attr(all_data$TE_Bel_4,"6") = "sehr"
attr(all_data$TE_Bel_5,"1") = "gar nicht"
attr(all_data$TE_Bel_5,"6") = "sehr"
attr(all_data$TE_Bel_6,"1") = "gar nicht"
attr(all_data$TE_Bel_6,"6") = "sehr"
attr(all_data$TE03_01,"1") = "gar nicht"
attr(all_data$TE03_01,"6") = "sehr"
attr(all_data$TE03_01,"-1") = "Ich habe mir keine Ziele gesetzt."
attr(all_data$TE06_01,"1") = "gar nicht"
attr(all_data$TE06_01,"6") = "sehr"
attr(all_data$TE06_01,"-1") = "Ich habe mir keinen Zeitplan gemacht."
attr(all_data$TE07_01,"1") = "gar nicht"
attr(all_data$TE07_01,"6") = "sehr"
attr(all_data$TE08_01,"1") = "gar nicht"
attr(all_data$TE08_01,"6") = "sehr"
attr(all_data$TE09_01,"1") = "gar nicht"
attr(all_data$TE09_01,"6") = "sehr"
attr(all_data$TE10_01,"1") = "gar nicht"
attr(all_data$TE10_01,"6") = "sehr"
attr(all_data$TE11_01,"1") = "gar nicht"
attr(all_data$TE11_01,"6") = "sehr"
attr(all_data$TE12_01,"1") = "gar nicht"
attr(all_data$TE12_01,"6") = "sehr"
attr(all_data$TE12_01,"-1") = "Ich hatte keinen Vorsatz gefasst."
attr(all_data$TE14_01,"1") = "gar nicht"
attr(all_data$TE14_01,"6") = "sehr"
attr(all_data$TE15_01,"1") = "gar nicht"
attr(all_data$TE15_01,"6") = "sehr"
attr(all_data$TE17_01,"1") = "gar nicht hilfreich"
attr(all_data$TE17_01,"6") = "sehr hilfreich"
attr(all_data$ZG01,"1") = "Start_in_den_Tag_1.jpg"
attr(all_data$ZG01,"2") = "Start_in_den_Tag_2.jpg"
attr(all_data$ZG01,"3") = "Start_in_den_Tag_3.jpg"
attr(all_data$ZG01,"4") = "Start_in_den_Tag_4.jpg"
attr(all_data$ZG01,"5") = "Start_in_den_Tag_5.jpg"
attr(all_data$ZG01,"6") = "Start_in_den_Tag_6.jpg"
attr(all_data$ZG01,"7") = "Start_in_den_Tag_7.jpg"
attr(all_data$ZG02,"1") = "Lernplaner_erfolgreich_vorbereitet_1.jpg"
attr(all_data$ZG02,"2") = "Lernplaner_erfolgreich_vorbereitet_2.jpg"
attr(all_data$ZG02,"3") = "Lernplaner_erfolgreich_vorbereitet_3.jpg"
attr(all_data$ZG02,"4") = "Lernplaner_erfolgreich_vorbereitet_4.jpg"
attr(all_data$ZG02,"5") = "Lernplaner_erfolgreich_vorbereitet_5.jpg"
attr(all_data$ZG02,"6") = "Lernplaner_erfolgreich_vorbereitet_6.jpg"
attr(all_data$ZG02,"7") = "Lernplaner_erfolgreich_vorbereitet_7.jpg"
attr(all_data$ZG03,"1") = "Beginn_Abendplaner_Checklist_1.jpg"
attr(all_data$ZG03,"2") = "Beginn_Abendplaner_Checklist_2.jpg"
attr(all_data$ZG03,"3") = "Beginn_Abendplaner_Checklist_3.jpg"
attr(all_data$ZG03,"4") = "Beginn_Abendplaner_Checklist_4.jpg"
attr(all_data$ZG03,"5") = "Beginn_Abendplaner_Checklist_5.jpg"
attr(all_data$ZG03,"6") = "Beginn_Abendplaner_Checklist_6.jpg"
attr(all_data$ZG03,"7") = "Beginn_Abendplaner_Checklist_7.jpg"
attr(all_data$ZG04,"1") = "Ende_des_Lerntags_1.jpg"
attr(all_data$ZG04,"2") = "Ende_des_Lerntags_2.jpg"
attr(all_data$ZG04,"3") = "Ende_des_Lerntags_3.jpg"
attr(all_data$ZG04,"4") = "Ende_des_Lerntags_4.jpg"
attr(all_data$ZG04,"5") = "Ende_des_Lerntags_5.jpg"
attr(all_data$ZG04,"6") = "Ende_des_Lerntags_6.jpg"
attr(all_data$ZG04,"7") = "Ende_des_Lerntags_7.jpg"
attr(all_data$ZG05,"1") = "Achtsamkeit_1.jpg"
attr(all_data$ZG05,"2") = "Achtsamkeit_2.jpg"
attr(all_data$ZG05,"3") = "Achtsamkeit_3.jpg"
attr(all_data$ZG05,"4") = "Achtsamkeit_4.jpg"
attr(all_data$ZG05,"5") = "Achtsamkeit_5.jpg"
attr(all_data$ZG05,"6") = "Achtsamkeit_6.jpg"
attr(all_data$ZG05,"7") = "Achtsamkeit_7.jpg"
attr(all_data$ZG06,"1") = "17.1_Zuf_minus_1"
attr(all_data$ZG06,"2") = "17.2_Zuf_minus_2"
attr(all_data$ZG06,"3") = "17.3_Zuf_minus_3"
attr(all_data$ZG06,"4") = "17.4_Zuf_minus_4"
attr(all_data$ZG07,"1") = "18.1_Zuf_0_1"
attr(all_data$ZG07,"2") = "18.2_Zuf_0_2"
attr(all_data$ZG07,"3") = "18.3_Zuf_0_3"
attr(all_data$ZG07,"4") = "18.4_Zuf_0_4"
attr(all_data$ZG08,"1") = "19.1_Zuf_plus_1"
attr(all_data$ZG08,"2") = "19.2_Zuf_plus_2"
attr(all_data$ZG08,"3") = "19.3_Zuf_plus_3"
attr(all_data$ZG08,"4") = "19.4_Zuf_plus_4"
attr(all_data$ZG09,"1") = "20.1_Zuf-minus_Mot-minus_1"
attr(all_data$ZG09,"2") = "20.2_Zuf-minus_Mot-minus_2"
attr(all_data$ZG09,"3") = "20.3_Zuf-minus_Mot-minus_3"
attr(all_data$ZG09,"4") = "20.4_Zuf-minus_Mot-minus_4"
attr(all_data$ZG10,"1") = "21.1_Zuf-minus_Mot-0_1"
attr(all_data$ZG10,"2") = "21.2_Zuf-minus_Mot-0_2"
attr(all_data$ZG10,"3") = "21.3_Zuf-minus_Mot-0_3"
attr(all_data$ZG10,"4") = "21.4_Zuf-minus_Mot-0_4"
attr(all_data$ZG11,"1") = "22.1_Zuf-minus_Mot-plus_1"
attr(all_data$ZG11,"2") = "22.2_Zuf-minus_Mot-plus_2"
attr(all_data$ZG11,"3") = "22.3_Zuf-minus_Mot-plus_3"
attr(all_data$ZG11,"4") = "22.4_Zuf-minus_Mot-plus_4"
attr(all_data$ZG15,"1") = "34.1_Zuf-plus_Mot-minus_1"
attr(all_data$ZG15,"2") = "34.2_Zuf-plus_Mot-minus_2"
attr(all_data$ZG15,"3") = "34.3_Zuf-plus_Mot-minus_3"
attr(all_data$ZG15,"4") = "34.4_Zuf-plus_Mot-minus_4"
attr(all_data$ZG16,"1") = "35.1_Zuf-plus_Mot-0_1"
attr(all_data$ZG16,"2") = "35.2_Zuf-plus_Mot-0_2"
attr(all_data$ZG16,"3") = "35.3_Zuf-plus_Mot-0_3"
attr(all_data$ZG16,"4") = "35.4_Zuf-plus_Mot-0_4"
attr(all_data$ZG17,"1") = "36.1_Zuf-plus_Mot-plus_1"
attr(all_data$ZG17,"2") = "36.2_Zuf-plus_Mot-plus_2"
attr(all_data$ZG17,"3") = "36.3_Zuf-plus_Mot-plus_3"
attr(all_data$ZG17,"4") = "36.4_Zuf-plus_Mot-plus_4"
attr(all_data$ZG18,"1") = "23.1_Zuf-minus_ZielE-minus_1"
attr(all_data$ZG18,"2") = "23.2_Zuf-minus_ZielE-minus_2"
attr(all_data$ZG18,"3") = "23.3_Zuf-minus_ZielE-minus_3"
attr(all_data$ZG18,"4") = "23.4_Zuf-minus_ZielE-minus_4"
attr(all_data$ZG19,"1") = "24.1_Zuf-minus_ZielE-0_1"
attr(all_data$ZG19,"2") = "24.2_Zuf-minus_ZielE-0_2"
attr(all_data$ZG19,"3") = "24.3_Zuf-minus_ZielE-0_3"
attr(all_data$ZG19,"4") = "24.4_Zuf-minus_ZielE-0_4"
attr(all_data$ZG20,"1") = "25.1_Zuf-minus_ZielE-plus_1"
attr(all_data$ZG20,"2") = "25.2_Zuf-minus_ZielE-plus_2"
attr(all_data$ZG20,"3") = "25.3_Zuf-minus_ZielE-plus_3"
attr(all_data$ZG20,"4") = "25.4_Zuf-minus_ZielE-plus_4"
attr(all_data$ZG21,"1") = "26.1_Zuf-minus_ZielE_Miss_1"
attr(all_data$ZG21,"2") = "26.2_Zuf-minus_ZielE_Miss_2"
attr(all_data$ZG21,"3") = "26.3_Zuf-minus_ZielE_Miss_3"
attr(all_data$ZG21,"4") = "26.4_Zuf-minus_ZielE_Miss_4"
attr(all_data$ZG22,"1") = "37.1_Zuf-plus_ZielE-minus_1"
attr(all_data$ZG22,"2") = "37.2_Zuf-plus_ZielE-minus_2"
attr(all_data$ZG22,"3") = "37.3_Zuf-plus_ZielE-minus_3"
attr(all_data$ZG22,"4") = "37.4_Zuf-plus_ZielE-minus_4"
attr(all_data$ZG23,"1") = "38.1_Zuf-plus_ZielE-0_1"
attr(all_data$ZG23,"2") = "38.2_Zuf-plus_ZielE-0_2"
attr(all_data$ZG23,"3") = "38.3_Zuf-plus_ZielE-0_3"
attr(all_data$ZG23,"4") = "38.4_Zuf-plus_ZielE-0_4"
attr(all_data$ZG24,"1") = "39.1_Zuf-plus_ZielE-plus_1"
attr(all_data$ZG24,"2") = "39.2_Zuf-plus_ZielE-plus_2"
attr(all_data$ZG24,"3") = "39.3_Zuf-plus_ZielE-plus_3"
attr(all_data$ZG24,"4") = "39.4_Zuf-plus_ZielE-plus_4"
attr(all_data$ZG25,"1") = "40.1_Zuf-plus_ZielE_Miss_1"
attr(all_data$ZG25,"2") = "40.2_Zuf-plus_ZielE_Miss_2"
attr(all_data$ZG25,"3") = "40.3_Zuf-plus_ZielE_Miss_3"
attr(all_data$ZG25,"4") = "40.4_Zuf-plus_ZielE_Miss_4"
attr(all_data$ZG26,"1") = "41.1_ZeitP-minus_1"
attr(all_data$ZG26,"2") = "41.2_ZeitP-minus_2"
attr(all_data$ZG26,"3") = "41.3_ZeitP-minus_3"
attr(all_data$ZG26,"4") = "41.4_ZeitP-minus_4"
attr(all_data$ZG27,"1") = "42.1_ZeitP-0_1"
attr(all_data$ZG27,"2") = "42.2_ZeitP-0_2"
attr(all_data$ZG27,"3") = "42.3_ZeitP-0_3"
attr(all_data$ZG27,"4") = "42.4_ZeitP-0_4"
attr(all_data$ZG28,"1") = "43.1_ZeitP-plus_1"
attr(all_data$ZG28,"2") = "43.2_ZeitP-plus_2"
attr(all_data$ZG28,"3") = "43.3_ZeitP-plus_3"
attr(all_data$ZG28,"4") = "43.4_ZeitP-plus_4"
attr(all_data$ZG29,"1") = "44.1_ZeitP_Miss_1"
attr(all_data$ZG29,"2") = "44.2_ZeitP_Miss_2"
attr(all_data$ZG29,"3") = "44.3_ZeitP_Miss_3"
attr(all_data$ZG29,"4") = "44.4_ZeitP_Miss_4"
attr(all_data$ZG30,"1") = "45.1_Pr-minus_1"
attr(all_data$ZG30,"2") = "45.2_Pr-minus_2"
attr(all_data$ZG30,"3") = "45.3_Pr-minus_3"
attr(all_data$ZG30,"4") = "45.4_Pr-minus_4"
attr(all_data$ZG31,"1") = "46.1_Pr-0_1"
attr(all_data$ZG31,"2") = "46.2_Pr-0_2"
attr(all_data$ZG31,"3") = "46.3_Pr-0_3"
attr(all_data$ZG31,"4") = "46.4_Pr-0_4"
attr(all_data$ZG32,"1") = "47.1_Pr-plus_1"
attr(all_data$ZG32,"2") = "47.2_Pr-plus_2"
attr(all_data$ZG32,"3") = "47.3_Pr-plus_3"
attr(all_data$ZG32,"4") = "47.4_Pr-plus_4"
attr(all_data$ZG33,"1") = "48.1_AnSt-minus_1"
attr(all_data$ZG33,"2") = "48.2_AnSt-minus_2"
attr(all_data$ZG33,"3") = "48.3_AnSt-minus_3"
attr(all_data$ZG33,"4") = "48.4_AnSt-minus_4"
attr(all_data$ZG34,"1") = "49.1_AnSt_0_1"
attr(all_data$ZG34,"2") = "49.2_AnSt_0_2"
attr(all_data$ZG34,"3") = "49.3_AnSt_0_3"
attr(all_data$ZG34,"4") = "49.4_AnSt_0_4"
attr(all_data$ZG35,"1") = "50.1_AnSt_plus_1"
attr(all_data$ZG35,"2") = "50.2_AnSt_plus_2"
attr(all_data$ZG35,"3") = "50.3_AnSt_plus_3"
attr(all_data$ZG35,"4") = "50.4_AnSt_plus_4"
attr(all_data$ZG36,"1") = "51.1_Kon-minus_1"
attr(all_data$ZG36,"2") = "51.2_Kon-minus_2"
attr(all_data$ZG36,"3") = "51.3_Kon-minus_3"
attr(all_data$ZG36,"4") = "51.4_Kon-minus_4"
attr(all_data$ZG37,"1") = "52.1_Kon-0_1"
attr(all_data$ZG37,"2") = "52.2_Kon-0_2"
attr(all_data$ZG37,"3") = "52.3_Kon-0_3"
attr(all_data$ZG37,"4") = "52.4_Kon-0_4"
attr(all_data$ZG38,"1") = "53.1_Kon-plus_1"
attr(all_data$ZG38,"2") = "53.2_Kon-plus_2"
attr(all_data$ZG38,"3") = "53.3_Kon-plus_3"
attr(all_data$ZG38,"4") = "53.4_Kon-plus_4"
attr(all_data$AV02_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV02_01,"6") = "stimme völlig zu"
attr(all_data$AV02_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV02_02,"6") = "stimme völlig zu"
attr(all_data$AV02_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV02_03,"6") = "stimme völlig zu"
attr(all_data$AV02_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV02_04,"6") = "stimme völlig zu"
attr(all_data$AV02_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV02_05,"6") = "stimme völlig zu"
attr(all_data$AV03_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV03_01,"6") = "stimme völlig zu"
attr(all_data$AV03_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV03_02,"6") = "stimme völlig zu"
attr(all_data$AV03_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV03_03,"6") = "stimme völlig zu"
attr(all_data$AV03_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV03_04,"6") = "stimme völlig zu"
attr(all_data$AV03_05,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV03_05,"6") = "stimme völlig zu"
attr(all_data$AV04_01,"1") = "gar nicht anspruchsvoll"
attr(all_data$AV04_01,"6") = "sehr anspruchsvoll"
attr(all_data$AV04_02,"1") = "gar nicht anspruchsvoll"
attr(all_data$AV04_02,"6") = "sehr anspruchsvoll"
attr(all_data$AV04_03,"1") = "gar nicht anspruchsvoll"
attr(all_data$AV04_03,"6") = "sehr anspruchsvoll"
attr(all_data$AV05_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV05_01,"6") = "stimme völlig zu"
attr(all_data$AV05_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV05_02,"6") = "stimme völlig zu"
attr(all_data$AV05_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV05_03,"6") = "stimme völlig zu"
attr(all_data$AV05_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV05_04,"6") = "stimme völlig zu"
attr(all_data$AV06_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV06_01,"6") = "stimme völlig zu"
attr(all_data$AV06_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV06_02,"6") = "stimme völlig zu"
attr(all_data$AV06_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV06_03,"6") = "stimme völlig zu"
attr(all_data$AV07_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV07_01,"6") = "stimme völlig zu"
attr(all_data$AV07_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV07_02,"6") = "stimme völlig zu"
attr(all_data$AV07_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV07_03,"6") = "stimme völlig zu"
attr(all_data$AV07_04,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV07_04,"6") = "stimme völlig zu"
attr(all_data$AV09_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV09_01,"6") = "stimme völlig zu"
attr(all_data$AV09_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV09_02,"6") = "stimme völlig zu"
attr(all_data$AV09_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV09_03,"6") = "stimme völlig zu"
attr(all_data$AV10_01,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV10_01,"6") = "stimme völlig zu"
attr(all_data$AV10_02,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV10_02,"6") = "stimme völlig zu"
attr(all_data$AV10_03,"1") = "stimme überhaupt nicht zu"
attr(all_data$AV10_03,"6") = "stimme völlig zu"
attr(all_data$FINISHED,"F") = "abgebrochen"
attr(all_data$FINISHED,"T") = "ausgefüllt"
attr(all_data$Q_VIEWER,"F") = "Teilnehmer"
attr(all_data$Q_VIEWER,"T") = "Durchklicker"
comment(all_data$SERIAL) = "Seriennummer (sofern verwendet)"
comment(all_data$REF) = "Referenz (sofern im Link angegeben)"
comment(all_data$QUESTNNR) = "Fragebogen, der im Interview verwendet wurde"
comment(all_data$MODE) = "Interview-Modus"
comment(all_data$STARTED) = "Zeitpunkt zu dem das Interview begonnen hat (Europe/Berlin)"
comment(all_data$EE02) = "Einverständnis"
comment(all_data$DD02_01) = "Alter: [01]"
comment(all_data$DD03) = "Geschlecht"
comment(all_data$DD04_01) = "Anzahl Fachsemester: [01]"
comment(all_data$DD05) = "Angestrebter Abschluss"
comment(all_data$DD05_12) = "Angestrebter Abschluss: Sonstiges"
comment(all_data$DD06_01) = "Studiengang: Hauptfach"
comment(all_data$DD06_02) = "Studiengang: Nebenfach"
comment(all_data$DD07) = "Abiturnote"
comment(all_data$DD09) = "Teilnahme_Methodenstudie"
comment(all_data$DD11) = "Teilnahme_Workshop"
comment(all_data$DD10_01) = "Vorwissen: Achtsamkeit"
comment(all_data$DD10_02) = "Vorwissen: kognitive Dissonanz"
comment(all_data$DD10_03) = "Vorwissen: Motivation"
comment(all_data$DD10_04) = "Vorwissen: Volition"
comment(all_data$DD10_05) = "Vorwissen: Konditionierung"
comment(all_data$DD10_06) = "Vorwissen: Intelligenzmessung"
comment(all_data$DD10_07) = "Vorwissen: Aufmerksamkeit"
comment(all_data$DD10_08) = "Vorwissen: Feedback"
comment(all_data$LP02_01) = "Termin_Prüfung_1: Bitte gib zunächst das Datum oder die Abgabefrist Deiner Leistungsüberprüfung an."
comment(all_data$LP03_01) = "Anspruch_Relevanz_1: Wie anspruchsvoll schätzt Du diese Leistungsüberprüfung ein?"
comment(all_data$LP03_02) = "Anspruch_Relevanz_1: Wie wichtig ist diese Leistungsüberprüfung für Dein Studium?"
comment(all_data$LP05) = "Note_Prüfung_1"
comment(all_data$LP06_01) = "Termin_Prüfung_2: Bitte gib zunächst das Datum oder die Abgabefrist Deiner Leistungsüberprüfung an."
comment(all_data$LP07_01) = "Anspruch_Relevanz_2: Wie anspruchsvoll schätzt Du diese Leistungsüberprüfung ein?"
comment(all_data$LP07_02) = "Anspruch_Relevanz_2: Wie wichtig ist diese Leistungsüberprüfung für Dein Studium?"
comment(all_data$LP09) = "Note_Prüfung_2"
comment(all_data$LP10_01) = "Termin_Prüfung_3: Bitte gib zunächst das Datum oder die Abgabefrist Deiner Leistungsüberprüfung an."
comment(all_data$LP11_01) = "Anspruch_Relevanz_3: Wie anspruchsvoll schätzt Du diese Leistungsüberprüfung ein?"
comment(all_data$LP11_02) = "Anspruch_Relevanz_3: Wie wichtig ist diese Leistungsüberprüfung für Dein Studium?"
comment(all_data$LP13) = "Note_Prüfung_3"
comment(all_data$T102_01) = "Zielsetzung: Ich habe feste Ziele im Leben."
comment(all_data$T102_02) = "Zielsetzung: Ich kann überprüfen, ob ich meine Ziele erreicht habe."
comment(all_data$T102_03) = "Zielsetzung: Ich wähle meine Ziele so, dass sie eine Herausforderung für mich sind."
comment(all_data$T102_04) = "Zielsetzung: Ich versuche, meine eigene Leistung von Mal zu Mal zu steigern."
comment(all_data$T103_01) = "Selbstmotivierung: Ich denke an frühere Erfolge zurück, um mein Selbstbewusstsein zu stärken."
comment(all_data$T103_02) = "Selbstmotivierung: Um mich zu motivieren, rufe ich mir vor Augen, wie schön es sein wird, wenn ich ein Ziel erreicht haben werde."
comment(all_data$T103_03) = "Selbstmotivierung: Ich suche mir vergangene Erfolgserlebnisse, um mich für schwierige Aufgaben zu motivieren."
comment(all_data$T104_01) = "Volition: Wenn mein Durchhaltevermögen nachlässt, weiß ich meist genau, wie ich meine Lust an der Sache verstärken kann."
comment(all_data$T104_02) = "Volition: Ich kann es schaffen, einer anfangs unangenehmen Tätigkeit zunehmend angenehme Seiten abzugewinnen."
comment(all_data$T104_03) = "Volition: Ich kann meine Stimmung so verändern, dass mir dann alles leichter von der Hand geht."
comment(all_data$T104_04) = "Volition: Ich kann mich beim Lernen gut in die Stimmung hineinbringen, die ich im Moment am besten gebrauchen kann."
comment(all_data$T105_01) = "Reflexion: Nach einer Lernwoche überlege ich, was ich alles gelernt habe."
comment(all_data$T105_02) = "Reflexion: Am Ende des Tages frage ich mich, ob ich mit meiner Leistung zufrieden bin."
comment(all_data$T105_03) = "Reflexion: Am Ende einer Woche denke ich darüber nach, welche Themen ich gekonnt habe und welche nicht."
comment(all_data$T106_01) = "Zeitplan: Beim Lernen halte ich mich an einen bestimmten Zeitplan."
comment(all_data$T106_02) = "Zeitplan: Ich lege die Stunden, die ich täglich mit Lernen verbringe, durch einen Zeitplan fest."
comment(all_data$T106_03) = "Zeitplan: Ich lege vor jeder Lernphase eine bestimmte Zeitdauer fest."
comment(all_data$T107_01) = "Prokrastination: Ich schiebe den Beginn von Aufgaben bis zum letzten Moment hinaus."
comment(all_data$T107_02) = "Prokrastination: Ich schiebe die Erledigung bestimmter Tätigkeiten vor mir her."
comment(all_data$T107_03) = "Prokrastination: Auch wenn ich mir vornehme mit einer Arbeit anzufangen, gelingt es mir nicht."
comment(all_data$T107_04) = "Prokrastination: Ich warte mit dem Beginn einer Arbeit so lange, dass es mir schwer fällt, sie noch rechtzeitig zu beenden."
comment(all_data$T107_05) = "Prokrastination: Beim Bearbeiten einer Aufgabe merke ich, dass ich sie schon viel früher hätte erledigen können."
comment(all_data$T107_06) = "Prokrastination: Ich fange mit einer Aufgabe erst an, wenn ich unter Druck gerate."
comment(all_data$T107_07) = "Prokrastination: Ich schaffe es erst auf den letzten Drücker meine Aufgaben zu erledigen."
comment(all_data$T108_01) = "Selbstwirksamkeit: Wenn im Studium unerwartete Situationen auftauchen, weiß ich immer, wie ich mich verhalten soll."
comment(all_data$T108_02) = "Selbstwirksamkeit: Für jedes Problem in meinem Studium habe ich eine Lösung."
comment(all_data$T108_03) = "Selbstwirksamkeit: Schwierigkeiten im Studium sehe ich gelassen entgegen, weil ich mich immer auf meine Fähigkeiten verlassen kann."
comment(all_data$T108_04) = "Selbstwirksamkeit: Wenn ich in meinem Studium mit einem Problem konfrontiert werde, habe ich meist mehrere Ideen, wie ich damit fertig werde."
comment(all_data$T108_05) = "Selbstwirksamkeit: Wenn ich in meinem Studium mit einer neuen Sache konfrontiert werde, weiß ich, wie ich damit umgehen kann."
comment(all_data$T108_06) = "Selbstwirksamkeit: Was auch immer in meinem Studium passiert, ich werde schon klarkommen."
comment(all_data$T108_07) = "Selbstwirksamkeit: Durch meine vergangenen Erfahrungen im Studium bin ich gut auf meine berufliche Zukunft vorbereitet."
comment(all_data$T108_08) = "Selbstwirksamkeit: Ich erreiche die studienbezogenen Ziele, die ich mir setze."
comment(all_data$T108_09) = "Selbstwirksamkeit: Ich fühle mich den meisten studienbezogenen Anforderungen gewachsen."
comment(all_data$T202_01) = "Zielsetzung: Ich habe feste Ziele im Leben."
comment(all_data$T202_02) = "Zielsetzung: Ich kann überprüfen, ob ich meine Ziele erreicht habe."
comment(all_data$T202_03) = "Zielsetzung: Ich wähle meine Ziele so, dass sie eine Herausforderung für mich sind."
comment(all_data$T202_04) = "Zielsetzung: Ich versuche, meine eigene Leistung von Mal zu Mal zu steigern."
comment(all_data$T203_01) = "Selbstmotivierung: Ich denke an frühere Erfolge zurück, um mein Selbstbewusstsein zu stärken."
comment(all_data$T203_02) = "Selbstmotivierung: Um mich zu motivieren, rufe ich mir vor Augen, wie schön es sein wird, wenn ich ein Ziel erreicht haben werde."
comment(all_data$T203_03) = "Selbstmotivierung: Ich suche mir vergangene Erfolgserlebnisse, um mich für schwierige Aufgaben zu motivieren."
comment(all_data$T204_01) = "Volition: Wenn mein Durchhaltevermögen nachlässt, weiß ich meist genau, wie ich meine Lust an der Sache verstärken kann."
comment(all_data$T204_02) = "Volition: Ich kann es schaffen, einer anfangs unangenehmen Tätigkeit zunehmend angenehme Seiten abzugewinnen."
comment(all_data$T204_03) = "Volition: Ich kann meine Stimmung so verändern, dass mir dann alles leichter von der Hand geht."
comment(all_data$T204_04) = "Volition: Ich kann mich beim Lernen gut in die Stimmung hineinbringen, die ich im Moment am besten gebrauchen kann."
comment(all_data$T205_01) = "Reflexion: Nach einer Lernwoche überlege ich, was ich alles gelernt habe."
comment(all_data$T205_02) = "Reflexion: Am Ende des Tages frage ich mich, ob ich mit meiner Leistung zufrieden bin."
comment(all_data$T205_03) = "Reflexion: Am Ende einer Woche denke ich darüber nach, welche Themen ich gekonnt habe und welche nicht."
comment(all_data$T206_01) = "Zeitplan: Beim Lernen halte ich mich an einen bestimmten Zeitplan."
comment(all_data$T206_02) = "Zeitplan: Ich lege die Stunden, die ich täglich mit Lernen verbringe, durch einen Zeitplan fest."
comment(all_data$T206_03) = "Zeitplan: Ich lege vor jeder Lernphase eine bestimmte Zeitdauer fest."
comment(all_data$T207_01) = "Prokrastination: Ich schiebe den Beginn von Aufgaben bis zum letzten Moment hinaus."
comment(all_data$T207_02) = "Prokrastination: Ich schiebe die Erledigung bestimmter Tätigkeiten vor mir her."
comment(all_data$T207_03) = "Prokrastination: Auch wenn ich mir vornehme mit einer Arbeit anzufangen, gelingt es mir nicht."
comment(all_data$T207_04) = "Prokrastination: Ich warte mit dem Beginn einer Arbeit so lange, dass es mir schwer fällt, sie noch rechtzeitig zu beenden."
comment(all_data$T207_05) = "Prokrastination: Beim Bearbeiten einer Aufgabe merke ich, dass ich sie schon viel früher hätte erledigen können."
comment(all_data$T207_06) = "Prokrastination: Ich fange mit einer Aufgabe erst an, wenn ich unter Druck gerate."
comment(all_data$T207_07) = "Prokrastination: Ich schaffe es erst auf den letzten Drücker meine Aufgaben zu erledigen."
comment(all_data$T208_01) = "Selbstwirksamkeit: Wenn im Studium unerwartete Situationen auftauchen, weiß ich immer, wie ich mich verhalten soll."
comment(all_data$T208_02) = "Selbstwirksamkeit: Für jedes Problem in meinem Studium habe ich eine Lösung."
comment(all_data$T208_03) = "Selbstwirksamkeit: Schwierigkeiten im Studium sehe ich gelassen entgegen, weil ich mich immer auf meine Fähigkeiten verlassen kann."
comment(all_data$T208_04) = "Selbstwirksamkeit: Wenn ich in meinem Studium mit einem Problem konfrontiert werde, habe ich meist mehrere Ideen, wie ich damit fertig werde."
comment(all_data$T208_05) = "Selbstwirksamkeit: Wenn ich in meinem Studium mit einer neuen Sache konfrontiert werde, weiß ich, wie ich damit umgehen kann."
comment(all_data$T208_06) = "Selbstwirksamkeit: Was auch immer in meinem Studium passiert, ich werde schon klarkommen."
comment(all_data$T208_07) = "Selbstwirksamkeit: Durch meine vergangenen Erfahrungen im Studium bin ich gut auf meine berufliche Zukunft vorbereitet."
comment(all_data$T208_08) = "Selbstwirksamkeit: Ich erreiche die studienbezogenen Ziele, die ich mir setze."
comment(all_data$T208_09) = "Selbstwirksamkeit: Ich fühle mich den meisten studienbezogenen Anforderungen gewachsen."
comment(all_data$KO01) = "Kontrollfrage"
comment(all_data$EM01_04) = "Kontaktdaten: Universitäts-Mailadresse: (Du wirst am 10.01. eine Bestätigungsmail erhalten.)"
comment(all_data$EM02) = "Zuordnung Seminar"
comment(all_data$EM03) = "Einführung"
comment(all_data$EM04) = "Zwischenreflexion"
comment(all_data$EV02_01) = "Evaluation Lernplaner: Es hat mich viel Überwindung gekostet, den Lernplaner auszufüllen."
comment(all_data$EV02_02) = "Evaluation Lernplaner: Der Lernplaner hat mir geholfen, meine Tage zu strukturieren."
comment(all_data$EV02_03) = "Evaluation Lernplaner: Der Lernplaner hat mir geholfen, über meinen Lernfortschritt nachzudenken."
comment(all_data$EV02_04) = "Evaluation Lernplaner: Der Lernplaner hat mir geholfen, mich zum Lernen zu motivieren."
comment(all_data$EV02_05) = "Evaluation Lernplaner: Ich würde in Zukunft in bestimmten Situationen wieder einen Lernplaner nutzen."
comment(all_data$EV02_06) = "Evaluation Lernplaner: Ich würde den Lernplaner weiterempfehlen."
comment(all_data$EV03_01) = "Offene Kommentare: [01]"
comment(all_data$EV04_01) = "Evaluation of Feedback_1: Das Feedback war hilfreich für mich."
comment(all_data$EV04_02) = "Evaluation of Feedback_1: Das Feedback hat mir neue Erkenntnisse über mein Lernverhalten verschafft."
comment(all_data$EV04_03) = "Evaluation of Feedback_1: Das Feedback hat mich motiviert, an meinem Lernverhalten etwas zu verändern."
comment(all_data$EV04_04) = "Evaluation of Feedback_1: Das Feedback hat mich frustriert."
comment(all_data$EV04_05) = "Evaluation of Feedback_1: Ich habe das Feedback bei der Planung des nächsten Tages berücksichtigt."
comment(all_data$FA02_01) = "CHIME: Wenn sich meine Stimmung verändert, nehme ich das sofort wahr."
comment(all_data$FA02_02) = "CHIME: Im Auf und Ab des Lebens bin ich mir gegenüber warmherzig."
comment(all_data$FA02_03) = "CHIME: Ich bemerke im Alltag, wenn eine bestimmte Situation erst durch meine negative Einstellung ihr gegenüber schwieriger wird."
comment(all_data$FA02_04) = "CHIME: Es ist mir klar, dass sich meine Bewertungen von Situationen oder Personen leicht verändern können."
comment(all_data$FA02_05) = "CHIME: Beim Sitzen oder Liegen nehme ich meine Körperempfindungen wahr."
comment(all_data$FA02_06) = "CHIME: Ich muss darüber schmunzeln, wenn ich sehe, wie ich mir manchmal die Dinge als viel komplizierter vorstelle, als sie eigentlich sind."
comment(all_data$FA02_07) = "CHIME: Ich gehe hart mit mir selber um, wenn ich Fehler mache. (umgepolt)"
comment(all_data$FA02_08) = "CHIME: Wenn ich belastende Gedanken oder Vorstellungen habe, fühle ich mich relativ schnell danach wieder ruhig."
comment(all_data$FA02_09) = "CHIME: Ich nehme Farben und Formen in der Natur deutlich und bewusst wahr."
comment(all_data$FA02_10) = "CHIME: Ich zerbreche oder verschütte Dinge aus Unachtsamkeit oder weil ich an anderes denke. (umgepolt)"
comment(all_data$FA02_11) = "CHIME: Ich sehe meine Fehler und Schwierigkeiten, ohne mich zu verurteilen."
comment(all_data$FA02_12) = "CHIME: Es fällt mir leicht, mich darauf zu konzentrieren, was ich tue."
comment(all_data$FA02_13) = "CHIME: Wenn ich belastende Gedanken oder Vorstellungen habe, kann ich sie einfach bemerken, ohne gleich auf sie zu reagieren."
comment(all_data$FA02_14) = "CHIME: Wenn ich mit anderen Personen spreche, nehme ich wahr, welche Gefühle ich dabei erlebe."
comment(all_data$FA02_15) = "CHIME: Wenn ich es mir selber unnötig schwer gemacht habe, kann ich das mit einer Spur Humor wahrnehmen."
comment(all_data$FA02_16) = "CHIME: In schwierigen Situationen kann ich einen Moment innehalten, ohne sofort zu reagieren."
comment(all_data$FA02_17) = "CHIME: Im Alltag werde ich durch viele Erinnerungen, Bilder oder Träumereinen abgelenkt. (umgepolt)"
comment(all_data$FA02_18) = "CHIME: Wenn ich Auto oder Zug fahre, bin ich mir meiner Umgebung, z.B. der Landschaft, bewusst."
comment(all_data$FA02_19) = "CHIME: Ich versuche beschäftigt zu bleiben, damit mir bestimmte Gedanken und Gefühle nicht bewusst werden. (umgepolt)"
comment(all_data$FA02_20) = "CHIME: Wenn ich in Gedanken und Gefühlen gefangen bin, dauert es nicht lange, bis ich das merke und mich wieder davon distanzieren kann."
comment(all_data$FA02_21) = "CHIME: Ich achte auf Empfindungen wie zum Beispiel Wind in meinem Haar oder Sonnenschein auf meinem Gesicht."
comment(all_data$FA02_22) = "CHIME: Ich versuche mich abzulenken, wenn ich unangenehme Gefühle erlebe. (umgepolt)"
comment(all_data$FA02_23) = "CHIME: Im Alltag ist mir bewusst, dass viele Gedanken Interpretationen sind, die nicht unbedingt der Realität entsprechen."
comment(all_data$FA02_24) = "CHIME: Ich kann darüber schmunzeln, wenn ich sehe, wie ich aus einer kleinen Schwierigkeit ein Problem gemacht habe."
comment(all_data$FA02_25) = "CHIME: Ich kann meine Gedanken und Gefühle beobachten, ohne mich in ihnen zu verstricken."
comment(all_data$FA02_26) = "CHIME: Beim Lesen muss ich Abschnitte wiederholt lesen, weil ich an etwas anderes gedacht habe. (umgepolt)"
comment(all_data$FA02_27) = "CHIME: Ich nehme Geräusche in meiner Umgebung, wie z.B. zwitschernde Vögel oder vorbeifahrende Autos, bewusst wahr."
comment(all_data$FA02_28) = "CHIME: Ich nehme meine Gefühle und Gedanken wahr und kann sie gleichzeitig mit etwas Distanz betrachten."
comment(all_data$FA02_29) = "CHIME: Ich nehme Veränderungen in meinem Körper deutlich wahr, z.B. schnelleres oder langsameres Atmen."
comment(all_data$FA02_30) = "CHIME: Ich mag es nicht, wenn ich ärgerlich oder ängstlich bin und versuche, solche Gefühle beiseite zu schieben. (umgepolt)"
comment(all_data$FA02_31) = "CHIME: Mir ist im Alltag bewusst, dass meine Sicht der Dinge subjektiv ist und den Tatsachen nicht entsprechen muss."
comment(all_data$FA02_32) = "CHIME: Auch wenn ich einen grossen Fehler gemacht habe, gehe ich mit mir auf eine verständnisvolle Art um."
comment(all_data$FA02_33) = "CHIME: Wenn ich Schmerzen habe, versuche ich diese Wahrnehmung möglichst zu vermeiden. (umgepolt)"
comment(all_data$FA02_34) = "CHIME: Es ist mir im Alltag bewusst, wie ich mich gerade fühle."
comment(all_data$FA02_35) = "CHIME: Es ist mir im Alltag bewusst, dass sich eigene Meinungen, die ich zur Zeit sehr ernst nehme, deutlich verändern können."
comment(all_data$FA02_36) = "CHIME: Ich nehme mir meine Fehler und Schwächen übel. (umgepolt)"
comment(all_data$FA02_37) = "CHIME: Wenn ich mir unnötig das Leben schwer mache, wird mir das bald danach klar."
comment(all_data$PT02) = "finale Note_Prüfung_1"
comment(all_data$PT03_01) = "Zufriedenheit_Note_1: Wie zufrieden bist Du mit dieser Note?"
comment(all_data$PT04) = "finale Note_Prüfung_2"
comment(all_data$PT05_01) = "Zufriedenheit_Note_2: Wie zufrieden bist Du mit dieser Note?"
comment(all_data$PT06) = "finale Note_Prüfung_3"
comment(all_data$PT07_01) = "Zufriedenheit_Note_3: Wie zufrieden bist Du mit dieser Note?"
comment(all_data$LZ02_01) = "Lernziele: [01]"
comment(all_data$LZ03_01) = "realistische Ziele: Sind Deine Ziele realistisch?"
comment(all_data$LZ04_01) = "anspruchsvolle Ziele: Sind Deine Ziele anspruchsvoll?"
comment(all_data$ZE02_01) = "Präsenzstudium: [01]"
comment(all_data$ZE03_01) = "Selbststudium: [01]"
comment(all_data$PL01_01) = "Planung_1: Ich habe einen konkreten Plan, nach dem ich heute meine studienrelevanten Aufgaben erledigen werde."
comment(all_data$PL02_01) = "Planung_2: [01]"
comment(all_data$SM02_01) = "Studienmotivation: Wie hoch schätzt Du heute Deine Studienmotivation ein?"
comment(all_data$SM02_02) = "Studienmotivation: Heute freue ich mich auf mein Studium und darauf, mich mit dessen Inhalten auseinanderzusetzen."
comment(all_data$SM02_03) = "Studienmotivation: Heute treibt mich zum Studium hauptsächlich der Druck, den ich habe."
comment(all_data$SE01_03) = "Selbstwirksamkeit: Ich bin mir sicher, dass ich heute alle Herausforderungen, die mein Studientag an mich stellt, meistern werde."
comment(all_data$TE_Bel_1) = "Belastung: Selbststudium"
comment(all_data$TE_Bel_2) = "Belastung: Präsenzstudium"
comment(all_data$TE_Bel_3) = "Belastung: Arbeit"
comment(all_data$TE_Bel_4) = "Belastung: Freizeit"
comment(all_data$TE_Bel_5) = "Belastung: Krankheit"
comment(all_data$TE_Bel_6) = "Belastung: Familie"
comment(all_data$TE03_01) = "Zielerreichung: Ich habe meine studienrelevanten Ziele für heute erreicht."
comment(all_data$TE04_01) = "tatsächliche Stunden Präsenz: [01]"
comment(all_data$TE05_01) = "Selbststudium tatsächliche Stunden: [01]"
comment(all_data$TE06_01) = "Zeitplan: Ich habe mich heute an meinen Zeitplan gehalten."
comment(all_data$TE07_01) = "Prokrastination: Unangenehme Aufgaben (studienrelevant) habe ich heute aufgeschoben."
comment(all_data$TE08_01) = "Anstrengung: Während meinen heutigen studienrelevanten Tätigkeiten (Präsenz- und Selbststudium) habe ich mich angestrengt."
comment(all_data$TE09_01) = "Konzentration: Während meinen heutigen studienrelevanten Tätigkeiten (Präsenz- und Selbststudium), war ich sehr konzentriert."
comment(all_data$TE10_01) = "Zufriedenheit: Mit dem, was ich heute geschafft habe (studienrelevant), bin ich sehr zufrieden."
comment(all_data$TE11_01) = "Überwachung: Heute habe ich mich selbst beobachtet, um zu prüfen ob ich meine Ressourcen (Zeit und Strategien) zielorientiert eingesetzt habe."
comment(all_data$TE12_01) = "Vorsatz: Ich habe heute meinen gestrigen gefassten Vorsatz erfolgreich umgesetzt."
comment(all_data$TE13_01) = "Vorsatz_2: [01]"
comment(all_data$TE14_01) = "Evaluation Tagebuch hilfreich: Der Lernplaner hat mir heute geholfen, meinen Tag zu strukturieren."
comment(all_data$TE15_01) = "Evaluation Tagebuch Spaß: Das Ausfüllen des Lernplaners hat heute Spaß gemacht."
comment(all_data$TE16) = "studienrelevante Tätigkeiten"
comment(all_data$TE17_01) = "Zufriedenheit Feedback: Wie hilfreich fandest Du das Feedback?"
comment(all_data$ZG01_CP) = "Bilder_Start_in_den_Tag: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG01) = "Bilder_Start_in_den_Tag: Gezogener Code"
comment(all_data$ZG02_CP) = "Bilder_Lernplaner_vorbereitet: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG02) = "Bilder_Lernplaner_vorbereitet: Gezogener Code"
comment(all_data$ZG03_CP) = "Bilder_Beginn_Abendplaner: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG03) = "Bilder_Beginn_Abendplaner: Gezogener Code"
comment(all_data$ZG04_CP) = "Bilder_Ende_Lerntag: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG04) = "Bilder_Ende_Lerntag: Gezogener Code"
comment(all_data$ZG05_CP) = "Bilder_Achtsamkeit: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG05) = "Bilder_Achtsamkeit: Gezogener Code"
comment(all_data$ZG06_CP) = "Zuf_minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG06) = "Zuf_minus: Gezogener Code"
comment(all_data$ZG07_CP) = "Zuf_0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG07) = "Zuf_0: Gezogener Code"
comment(all_data$ZG08_CP) = "Zuf_plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG08) = "Zuf_plus: Gezogener Code"
comment(all_data$ZG09_CP) = "Zuf-minus_Mot-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG09) = "Zuf-minus_Mot-minus: Gezogener Code"
comment(all_data$ZG10_CP) = "Zuf-minus_Mot-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG10) = "Zuf-minus_Mot-0: Gezogener Code"
comment(all_data$ZG11_CP) = "Zuf-minus_Mot-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG11) = "Zuf-minus_Mot-plus: Gezogener Code"
comment(all_data$ZG15_CP) = "Zuf-plus_Mot-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG15) = "Zuf-plus_Mot-minus: Gezogener Code"
comment(all_data$ZG16_CP) = "Zuf-plus_Mot-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG16) = "Zuf-plus_Mot-0: Gezogener Code"
comment(all_data$ZG17_CP) = "Zuf-plus_Mot-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG17) = "Zuf-plus_Mot-plus: Gezogener Code"
comment(all_data$ZG18_CP) = "Zuf-minus_ZielE-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG18) = "Zuf-minus_ZielE-minus: Gezogener Code"
comment(all_data$ZG19_CP) = "Zuf-minus_ZielE-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG19) = "Zuf-minus_ZielE-0: Gezogener Code"
comment(all_data$ZG20_CP) = "Zuf-minus_ZielE-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG20) = "Zuf-minus_ZielE-plus: Gezogener Code"
comment(all_data$ZG21_CP) = "Zuf-minus_ZielE-Miss: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG21) = "Zuf-minus_ZielE-Miss: Gezogener Code"
comment(all_data$ZG22_CP) = "Zuf-plus_ZielE-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG22) = "Zuf-plus_ZielE-minus: Gezogener Code"
comment(all_data$ZG23_CP) = "Zuf-plus_ZielE-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG23) = "Zuf-plus_ZielE-0: Gezogener Code"
comment(all_data$ZG24_CP) = "Zuf-plus_ZielE-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG24) = "Zuf-plus_ZielE-plus: Gezogener Code"
comment(all_data$ZG25_CP) = "Zuf-plus_ZielE-Miss: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG25) = "Zuf-plus_ZielE-Miss: Gezogener Code"
comment(all_data$ZG26_CP) = "ZeitP-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG26) = "ZeitP-minus: Gezogener Code"
comment(all_data$ZG27_CP) = "ZeitP-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG27) = "ZeitP-0: Gezogener Code"
comment(all_data$ZG28_CP) = "ZeitP-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG28) = "ZeitP-plus: Gezogener Code"
comment(all_data$ZG29_CP) = "ZeitP-Miss: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG29) = "ZeitP-Miss: Gezogener Code"
comment(all_data$ZG30_CP) = "Pr-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG30) = "Pr-minus: Gezogener Code"
comment(all_data$ZG31_CP) = "Pr-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG31) = "Pr-0: Gezogener Code"
comment(all_data$ZG32_CP) = "Pr-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG32) = "Pr-plus: Gezogener Code"
comment(all_data$ZG33_CP) = "AnSt-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG33) = "AnSt-minus: Gezogener Code"
comment(all_data$ZG34_CP) = "AnSt-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG34) = "AnSt-0: Gezogener Code"
comment(all_data$ZG35_CP) = "AnSt-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG35) = "AnSt-plus: Gezogener Code"
comment(all_data$ZG36_CP) = "Kon-minus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG36) = "Kon-minus: Gezogener Code"
comment(all_data$ZG37_CP) = "Kon-0: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG37) = "Kon-0: Gezogener Code"
comment(all_data$ZG38_CP) = "Kon-plus: Vollständige Leerungen der Urne bisher"
comment(all_data$ZG38) = "Kon-plus: Gezogener Code"
comment(all_data$AI01_pts) = "Markierungen (Positionen x1,y1,m1 x2,y2,m2 ...)"
comment(all_data$AI01_rgs) = "Bereiche der Markierungen"
comment(all_data$AI01_01) = "Wahrnehmung_Atem_1:  (Anzahl insgesamt)"
comment(all_data$AI02_01) = "Wahrnehmung_Atem_2: [01]"
comment(all_data$AI06_01) = "Textfeld_Hirnbaum: [01]"
comment(all_data$AI12_01) = "Hinweis_zu schnell: [01]"
comment(all_data$AV02_01) = "Belastung/Stress: Ich fühle mich im Studium oft erschöpft."
comment(all_data$AV02_02) = "Belastung/Stress: Ich empfinde es als Problem, so viele Fächer belegen zu müssen."
comment(all_data$AV02_03) = "Belastung/Stress: Ich merke öfter im Studium, wie lustlos ich bin."
comment(all_data$AV02_04) = "Belastung/Stress: Ich fühle mich insgesamt überlastet."
comment(all_data$AV02_05) = "Belastung/Stress: Manchmal bin ich am Ende des Studientages richtig deprimiert."
comment(all_data$AV03_01) = "Zufriedenheit im Studium: Ich habe mir nicht nur einmal überlegt, ob es für mich nicht besser gewesen wäre, einen anderen Studiengang zu wählen."
comment(all_data$AV03_02) = "Zufriedenheit im Studium: Ich bin mit meinem Studium sehr zufrieden."
comment(all_data$AV03_03) = "Zufriedenheit im Studium: Für mich gibt es keinen besseren Studiengang."
comment(all_data$AV03_04) = "Zufriedenheit im Studium: Ich würde in einen anderen Studiengang wechseln, wenn ich die Möglichkeit dazu hätte."
comment(all_data$AV03_05) = "Zufriedenheit im Studium: Wenn ich noch einmal wählen könnte, würde ich sofort wieder den gleichen Studiengang wählen."
comment(all_data$AV04_01) = "4 Studienanforderung: ... hinsichtlich des fachlichen Anforderungsniveaus?"
comment(all_data$AV04_02) = "4 Studienanforderung: ... hinsichtlich der Selbstständigkeit in der Studiengestaltung?"
comment(all_data$AV04_03) = "4 Studienanforderung: ... hinsichtlich der Menge an Lernstoff?"
comment(all_data$AV05_01) = "Planung: Ich setze mir feste Zeitpunkte, zu denen ich meine Ziele erreichen will."
comment(all_data$AV05_02) = "Planung: Wenn ich viel zu lernen habe, mache ich mir einen Zeitplan, was ich wann lerne."
comment(all_data$AV05_03) = "Planung: Ich lerne immer zu gleich bleibenden Zeiten."
comment(all_data$AV05_04) = "Planung: Alle wichtigen Termine und Aufgaben schreibe ich mir auf."
comment(all_data$AV06_01) = "Elaboration: Ich versuche, Beziehungen zu den Inhalten verwandter Fächer bzw. Lehrveranstaltungen herzustellen."
comment(all_data$AV06_02) = "Elaboration: Zu neuen Konzepten stelle ich mir praktische Anwendungen vor."
comment(all_data$AV06_03) = "Elaboration: Ich versuche in Gedanken das Gelernte mit dem zu verbinden, was ich schon darüber weiß."
comment(all_data$AV07_01) = "Metakognition: Ich beginne erst mit dem Lernen, wenn ich mir die notwendigen Einzelschritte klargemacht habe."
comment(all_data$AV07_02) = "Metakognition: Ich denke regelmäßig über mein Lernen nach."
comment(all_data$AV07_03) = "Metakognition: Ich mache mir Aufzeichnungen über mein Lernverhalten."
comment(all_data$AV07_04) = "Metakognition: Ich notiere mir Strategien, die ich beim Lernen ausprobieren möchte."
comment(all_data$AV09_01) = "Lernumgebung: Ich lerne an einem Ort, wo ich mich gut auf den Lernstoff konzentrieren kann."
comment(all_data$AV09_02) = "Lernumgebung: Wenn ich lerne, sorge ich dafür, dass ich alles schnell finden kann."
comment(all_data$AV09_03) = "Lernumgebung: Ich gestalte meine Lernumgebung so, dass ich möglichst wenig vom Lernen abgelenkt werde."
comment(all_data$AV10_01) = "Regulation: Wenn ich merke, dass ich besser zuerst etwas anderes lernen sollte, ändere ich die Abfolge entsprechend."
comment(all_data$AV10_02) = "Regulation: Ich verändere meine Lerntechnik, wenn ich auf Schwierigkeiten stoße."
comment(all_data$AV10_03) = "Regulation: Wenn ich merke, dass ich etwas falsch verstanden habe, arbeite ich diesen Teil noch einmal durch."
comment(all_data$TIME001) = "Verweildauer Seite 1"
comment(all_data$TIME002) = "Verweildauer Seite 2"
comment(all_data$TIME003) = "Verweildauer Seite 3"
comment(all_data$TIME004) = "Verweildauer Seite 4"
comment(all_data$TIME005) = "Verweildauer Seite 5"
comment(all_data$TIME006) = "Verweildauer Seite 6"
comment(all_data$TIME007) = "Verweildauer Seite 7"
comment(all_data$TIME008) = "Verweildauer Seite 8"
comment(all_data$TIME009) = "Verweildauer Seite 9"
comment(all_data$TIME010) = "Verweildauer Seite 10"
comment(all_data$TIME011) = "Verweildauer Seite 11"
comment(all_data$TIME012) = "Verweildauer Seite 12"
comment(all_data$TIME013) = "Verweildauer Seite 13"
comment(all_data$TIME014) = "Verweildauer Seite 14"
comment(all_data$TIME015) = "Verweildauer Seite 15"
comment(all_data$TIME016) = "Verweildauer Seite 16"
comment(all_data$TIME017) = "Verweildauer Seite 17"
comment(all_data$TIME018) = "Verweildauer Seite 18"
comment(all_data$TIME019) = "Verweildauer Seite 19"
comment(all_data$TIME_SUM) = "Verweildauer gesamt (ohne Ausreißer)"
comment(all_data$MAILSENT) = "Versandzeitpunkt der Einladungsmail (nur für nicht-anonyme Adressaten)"
comment(all_data$LASTDATA) = "Zeitpunkt als der Datensatz das letzte mal geändert wurde"
comment(all_data$FINISHED) = "Wurde die Befragung abgeschlossen (letzte Seite erreicht)?"
comment(all_data$Q_VIEWER) = "Hat der Teilnehmer den Fragebogen nur angesehen, ohne die Pflichtfragen zu beantworten?"
comment(all_data$LASTPAGE) = "Seite, die der Teilnehmer zuletzt bearbeitet hat"
comment(all_data$MAXPAGE) = "Letzte Seite, die im Fragebogen bearbeitet wurde"
comment(all_data$MISSING) = "Anteil fehlender Antworten in Prozent"
comment(all_data$MISSREL) = "Anteil fehlender Antworten (gewichtet nach Relevanz)"
comment(all_data$TIME_RSI) = "Maluspunkte für schnelles Ausfüllen"
comment(all_data$DEG_TIME) = "Maluspunkte für schnelles Ausfüllen"



# Assure that the comments are retained in subsets
as.data.frame.avector = as.data.frame.vector
`[.avector` <- function(x,i,...) {
  r <- NextMethod("[")
  mostattributes(r) <- attributes(x)
  r
}
all_data_tmp = data.frame(
  lapply(all_data, function(x) {
    structure( x, class = c("avector", class(x) ) )
  } )
)
mostattributes(all_data_tmp) = attributes(all_data)
all_data = all_data_tmp
rm(all_data_tmp)

